#ifndef FZ_PREPROCESSOR_STR_HPP
#define FZ_PREPROCESSOR_STR_HPP

#define FZ_PP_STR(...) FZ_INTERNAL_PP_STR(__VA_ARGS__)

#define FZ_INTERNAL_PP_STR(...) #__VA_ARGS__

#endif // FZ_PREPROCESSOR_STR_HPP
